version: "3"
services:
  backend:
    build: ./server
    ports:
      - "3001:3001"

  frontend:
    build: ./frontend/client
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - backend
